from pydantic import BaseModel
from typing import Optional

class ProjectIn(BaseModel):
    user_id: str                      # ✅ Required for summary deletion, association, etc.
    student_name: Optional[str] = None
    title: str
    description: str
    file_url: Optional[str] = None

class ProjectOut(ProjectIn):
    id: int                           # Auto-generated by the database
